# build.yaml

targets:
  $default:
    sources:
      - graphql/**
      - lib/**
      - pubspec.*
      - $package$
    builders:
      graphql_codegen:
        options:
          scalars:
            URL:
              type: String
            Timestamp:
              type: String
            Upload:
              type: String
            Time:
              type: String
            Map:
              type: Map
            Int64:
              type: int
          clients:
            - graphql
          outputDirectory: /lib/graphql
          assetsPath: graphql/stash/graphql/**.graphql
          addTypenameExcludedPaths:
            - stash-box
