name: stashhub
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_platform_widgets: ^3.3.2
  graphql: ^5.1.3
  graphql_flutter: ^5.1.2
  infinite_scroll_pagination: ^3.2.0
  provider: ^6.0.5
  swipe_image_gallery: ^0.8.3
  flutter_native_splash: ^2.2.19
  collection: ^1.17.1

  dynamic_color: ^1.6.3
  adaptive_navigation: ^0.0.9
  adaptive_breakpoints: ^0.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  graphql_codegen: ^0.12.2
  build_runner: ^2.4.1

flutter:
  uses-material-design: true
